before_commands:
    - "composer install --prefer-source"

filter:
    excluded_paths: [vendor/*, app/*, web/*]

tools:
    js_hint: false
    php_mess_detector: true
    php_cs_fixer:
        config:
            level: all
    php_code_sniffer: true
    sensiolabs_security_checker: false
    php_code_coverage:
        test_command: phpunit
        config_path: null
    php_cpd: true
    php_loc: true
    php_pdepend: true
    external_code_coverage: false
